global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'docker-host-alpha'

scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
     - targets: ['192.168.50.10:9100', '192.168.50.20:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.50.10:8080', '192.168.50.20:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
